package main

import (
	"samplegofiber/src/handlers"

	swagger "github.com/arsmn/fiber-swagger"
	_ "github.com/arsmn/fiber-swagger/v2/example/docs" // docs is generated by Swag CLI, you have
	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()

	app.Use("/swagger", swagger.Handler)
	app.Use("/swagger", swagger.New(swagger.Config{
		URL:         "http://example.com/doc.json",
		DeepLinking: false,
	}))

	app.Get("/", func(c *fiber.Ctx) {
		c.Status(200).Send("Eu estou funcionando...")
	})
	app.Post("/person", handlers.NewPersonHandle)

	println("Running on http://0.0.0.0/8080")
	app.Listen(8080)
}
