apiVersion: v1
kind: Service
metadata:
    name: personapi-service
    namespace: estudos
spec:
    selector:
        app: personapi
    ports:
        - port: 3000
          targetPort: 3000
    type: LoadBalancer
